version: '3.8'
services:
  postgres:
    image: postgres:13  # Use the desired version of PostgreSQL
    environment:
      POSTGRES_DB: mydatabase     # Set the name of your database
      POSTGRES_USER: myuser       # Set the user for the database
      POSTGRES_PASSWORD: mypass   # Set the password for the database
    ports:
      - "5432:5432"  # Map the default PostgreSQL port to the host
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist database data

volumes:
  pgdata:
