version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  fastapi-app:
    build: .
    environment:
      DATABASE_URL: postgresql://myuser:mypass@postgres/mydatabase
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - .:/code
      - ./app:/code/app

volumes:
  pgdata:
