"""users + institute + donation + cause

Revision ID: f709e9b0d5cc
Revises: 7941105f7080
Create Date: 2024-04-04 21:20:31.304091

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f709e9b0d5cc'
down_revision: Union[str, None] = '7941105f7080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'institute',
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('cnpj', sa.String(length=14), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_institute_cnpj'), 'institute', ['cnpj'], unique=True)
    op.create_index(op.f('ix_institute_email'), 'institute', ['email'], unique=True)
    op.create_table(
        'causes',
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('image_links', sa.JSON(), nullable=True),
        sa.Column('payment_link', sa.String(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('institute_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['institute_id'],
            ['institute.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_causes_id'), 'causes', ['id'], unique=False)
    op.create_table(
        'donations',
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('is_paid', sa.Boolean(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('cause_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['cause_id'],
            ['causes.id'],
        ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_donations_id'), 'donations', ['id'], unique=False)
    op.drop_index('ix_items_description', table_name='items')
    op.drop_index('ix_items_title', table_name='items')
    op.drop_table('items')
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('cpf', sa.String(length=11), nullable=True))
    op.add_column('users', sa.Column('institute_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_cpf'), 'users', ['cpf'], unique=True)
    op.create_foreign_key(None, 'users', 'institute', ['institute_id'], ['id'])
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_cpf'), table_name='users')
    op.drop_column('users', 'institute_id')
    op.drop_column('users', 'cpf')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.create_table(
        'items',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='items_owner_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='items_pkey'),
    )
    op.create_index('ix_items_title', 'items', ['title'], unique=False)
    op.create_index('ix_items_description', 'items', ['description'], unique=False)
    op.drop_index(op.f('ix_donations_id'), table_name='donations')
    op.drop_table('donations')
    op.drop_index(op.f('ix_causes_id'), table_name='causes')
    op.drop_table('causes')
    op.drop_index(op.f('ix_institute_email'), table_name='institute')
    op.drop_index(op.f('ix_institute_cnpj'), table_name='institute')
    op.drop_table('institute')
    # ### end Alembic commands ###
