name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: AI Code Reviewer
      uses: pedro-lucinda/ai-codereviewer@main
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OPENAI_API_MODEL: "gpt-4" # Optional: defaults to "gpt-4"
        exclude: "**/*.json, **/*.md, **/alembic, **/*.sh" 
    - name: Lint with pylint
      run: |
        pip install pylint
        pylint --rcfile=.pylintrc app/
